version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
    environment:
      - SQLITE_DATABASE_URL=sqlite:///database/weekend-overtime.sqlite
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  database:
